
////////////////////////////////////////////
// Generated by BRCC v0.1
// BRCC Compiled on: Sep 29 2008 17:37:58
////////////////////////////////////////////

#include "brook/brook.hpp"
#include "brook_gpu.hpp"
#include <windows.h>

int  main(int  argc, char  **argv)
{		

  int  wx = 4096;
  int  wy = 4096;
  double  t;

  HMODULE lib; 
	
  lib = LoadLibrary(L"ATIGPU.dll");
  FreeLibrary(lib);

/*
  float  *inputA = (float *) (malloc(wx * wy * sizeof(float ) ));

  {
    ::brook::stream streamA(::brook::getStreamType(( float  *)0), wx , wy,-1);
    ::brook::stream streamB(::brook::getStreamType(( float  *)0), wx , wy,-1);

    t = GetTickCount();
    streamRead(streamA, inputA);
    streamRead(streamB, inputA);
    t = GetTickCount() - t;
  }

  free(inputA);
*/
  return 0;
}

